# parts snarfled from:
# https://gist.github.com/lukasbach/abb194a1b7b109742a25c18aa9f9a398

name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: book
          root_file: plainmath.tex
      - name: Copy
        run: |
            mkdir out
            cp ./book/plainmath.pdf ./out/plainmath.pdf
      - uses: actions/upload-artifact@v4
        with:
              name: plainmath
              path: out/plainmath.pdf
              retention-days: 5
